<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Includes -->
   <xacro:include filename="inertial_macros.xacro" />

  <!-- Camera Link -->
    <joint name = "camera_joint" type = "fixed">
        <parent link = "sensor_tower_link"/>
        <child link = "camera_link"/>
        <origin xyz = "${size_item*7/6} 0 0"/>
    </joint>

    <link name = "camera_link">
        <visual>
            <origin xyz = "${-3*size_item/6} 0 0"/>
            <geometry>
                <box size = "${size_item/3} ${size_item} ${size_item}"/>
            </geometry>
            <material name = "orange"/>
        </visual>
       <xacro:inertial_box mass="0.025" x="${size_item*2/3}" y="${size_item}" z="${size_item}">
            <origin xyz= "${-size_item/3} 0 0"  rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <origin xyz = "${-size_item/6} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${size_item/3}" length = "${size_item/3}"/>
            </geometry>
            <material name = "orange"/>
        </visual>
     
        <collision>
            <geometry>
                <box size = "${size_item*2/3} ${size_item} ${size_item}"/>
            </geometry>
        </collision>
    </link>

    <joint name = "camera_optical_joint" type = "fixed">
        <parent link = "camera_link"/>
        <child link = "camera_optical_link"/>
        <origin xyz = "0 0 0" rpy = "${-pi/2} 0 ${-pi/2}"/>
    </joint>


     <link name = "camera_optical_link"> </link>

    <gazebo reference = "camera_link">
        <material>Gazebo/Orange</material>
        <sensor name="camera" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_optical_link</frame_name>
            </plugin>
        </sensor>        
    </gazebo>

</robot>

