<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <!-- Includes -->
   <xacro:include filename="inertial_macros.xacro" />

 

        <!-- Lidar Link -->
    <joint name = "laser_joint" type = "fixed">
        <parent link = "sensor_tower_link"/>
        <child link = "laser_link"/>
        <origin xyz = "${-2*size_item} 0 ${hight_sensor_tower/2}"/>
    </joint>

    <link name = "laser_link">
        <visual>
            <origin xyz = "0 0 ${-size_item/4}"/>
            <geometry>
                <box size = "${size_item*3} ${size_item*2} ${size_item/2}"/>
            </geometry>
            <material name = "green"/>
        </visual>
       <xacro:inertial_box mass="0.1" x="${size_item*3}" y="${size_item*2}" z="${size_item*7/6}">
            <origin xyz= "0 0 ${-size_item/12}"  rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <origin xyz = "0 0 ${size_item/4}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${size_item*0.75}" length = "${size_item*2/3}"/>
            </geometry>
            <material name = "orange"/>
        </visual>
     
        <collision>
            <origin xyz= "0 0 ${-size_item/12}"  rpy="0 0 0"/>
            <geometry>
                <box size = "${size_item*3} ${size_item*2} ${size_item*7/6}"/>
            </geometry>
        </collision>
    </link>

    <gazebo reference = "laser_link">
        <material>Gazebo/Green</material>
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan
                </output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>        
    </gazebo>

</robot>

